"""Initial migration - create all tables

Revision ID: 872a616e100d
Revises: 
Create Date: 2025-12-19 12:57:56.453866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '872a616e100d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_index_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('period', sa.String(length=10), nullable=True),
    sa.Column('interval', sa.String(length=10), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_index_date', 'cached_index_data', ['index_id', 'date'], unique=False)
    op.create_index('idx_index_period', 'cached_index_data', ['index_id', 'period', 'interval'], unique=False)
    op.create_index(op.f('ix_cached_index_data_id'), 'cached_index_data', ['id'], unique=False)
    op.create_index(op.f('ix_cached_index_data_index_id'), 'cached_index_data', ['index_id'], unique=False)
    op.create_table('index_quote_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('previous_close', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('day_high', sa.Float(), nullable=True),
    sa.Column('day_low', sa.Float(), nullable=True),
    sa.Column('fifty_two_week_high', sa.Float(), nullable=True),
    sa.Column('fifty_two_week_low', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_id')
    )
    op.create_index(op.f('ix_index_quote_cache_id'), 'index_quote_cache', ['id'], unique=False)
    op.create_table('prediction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.String(length=50), nullable=False),
    sa.Column('prediction_date', sa.DateTime(), nullable=True),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.Column('prediction_days', sa.Integer(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('predicted_price', sa.Float(), nullable=True),
    sa.Column('actual_price', sa.Float(), nullable=True),
    sa.Column('predicted_direction', sa.String(length=20), nullable=True),
    sa.Column('predicted_change_percent', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('technical_factors', sa.JSON(), nullable=True),
    sa.Column('sentiment_factors', sa.JSON(), nullable=True),
    sa.Column('combined_signal', sa.Float(), nullable=True),
    sa.Column('actual_direction', sa.String(length=20), nullable=True),
    sa.Column('actual_change_percent', sa.Float(), nullable=True),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prediction_index_target', 'prediction_logs', ['index_id', 'target_date'], unique=False)
    op.create_index('idx_prediction_pending', 'prediction_logs', ['actual_price'], unique=False)
    op.create_index(op.f('ix_prediction_logs_id'), 'prediction_logs', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_logs_index_id'), 'prediction_logs', ['index_id'], unique=False)
    op.create_table('sentiment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.String(length=50), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('overall_sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('total_articles', sa.Integer(), nullable=True),
    sa.Column('positive_count', sa.Integer(), nullable=True),
    sa.Column('negative_count', sa.Integer(), nullable=True),
    sa.Column('neutral_count', sa.Integer(), nullable=True),
    sa.Column('articles', sa.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sentiment_index_date', 'sentiment_history', ['index_id', 'analyzed_at'], unique=False)
    op.create_index(op.f('ix_sentiment_history_analyzed_at'), 'sentiment_history', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_sentiment_history_id'), 'sentiment_history', ['id'], unique=False)
    op.create_index(op.f('ix_sentiment_history_index_id'), 'sentiment_history', ['index_id'], unique=False)
    op.create_table('user_watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('index_id', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('show_in_dashboard', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_watchlist', 'user_watchlist', ['user_id', 'index_id'], unique=True)
    op.create_index(op.f('ix_user_watchlist_id'), 'user_watchlist', ['id'], unique=False)
    op.create_index(op.f('ix_user_watchlist_user_id'), 'user_watchlist', ['user_id'], unique=False)
    op.drop_index('legal_cases_case_id_key', table_name='legal_cases')
    op.drop_table('legal_cases')
    op.drop_table('call_logs')
    op.drop_table('bots')
    op.drop_index('clients_client_id_key', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='clients_pkey')
    )
    op.create_index('clients_client_id_key', 'clients', ['client_id'], unique=False)
    op.create_table('bots',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('openmic_bot_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('webhook_urls', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='bots_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('call_logs',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('bot_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('call_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('case_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'completed'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name='call_logs_bot_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='call_logs_pkey')
    )
    op.create_table('legal_cases',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('client_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('case_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('attorney', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='legal_cases_pkey')
    )
    op.create_index('legal_cases_case_id_key', 'legal_cases', ['case_id'], unique=False)
    op.drop_index(op.f('ix_user_watchlist_user_id'), table_name='user_watchlist')
    op.drop_index(op.f('ix_user_watchlist_id'), table_name='user_watchlist')
    op.drop_index('idx_user_watchlist', table_name='user_watchlist')
    op.drop_table('user_watchlist')
    op.drop_index(op.f('ix_sentiment_history_index_id'), table_name='sentiment_history')
    op.drop_index(op.f('ix_sentiment_history_id'), table_name='sentiment_history')
    op.drop_index(op.f('ix_sentiment_history_analyzed_at'), table_name='sentiment_history')
    op.drop_index('idx_sentiment_index_date', table_name='sentiment_history')
    op.drop_table('sentiment_history')
    op.drop_index(op.f('ix_prediction_logs_index_id'), table_name='prediction_logs')
    op.drop_index(op.f('ix_prediction_logs_id'), table_name='prediction_logs')
    op.drop_index('idx_prediction_pending', table_name='prediction_logs')
    op.drop_index('idx_prediction_index_target', table_name='prediction_logs')
    op.drop_table('prediction_logs')
    op.drop_index(op.f('ix_index_quote_cache_id'), table_name='index_quote_cache')
    op.drop_table('index_quote_cache')
    op.drop_index(op.f('ix_cached_index_data_index_id'), table_name='cached_index_data')
    op.drop_index(op.f('ix_cached_index_data_id'), table_name='cached_index_data')
    op.drop_index('idx_index_period', table_name='cached_index_data')
    op.drop_index('idx_index_date', table_name='cached_index_data')
    op.drop_table('cached_index_data')
    # ### end Alembic commands ###
